# Generated by Django 4.0.5 on 2022-08-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0011_profile_github_url_profile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
